version: "3.7"
services:
  api:
    build:
      context: ./source
      dockerfile: Dockerfile
      target: final
    ports:
      - 5271:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  integrationtests:
    build:
      context: ./source
      dockerfile: Dockerfile
      target: integrationtestrunner
    environment:
      API_PATH: http://api
    depends_on:
      api:
        condition: service_healthy
  unittests:
    build:
      context: ./source
      dockerfile: Dockerfile
      target: unittestrunner
